### ISSUE TITLE
encodedUrl fail for some PWAs

### ISSUE THREAD

**Issue by juliantoledo** [GoogleChromeLabs/gulliver#420]
regarding #417, few PWAs are not found by encodedUrl, for example: 
http://localhost:8080/pwas/www.fidgetspin.xyz%2F

{ TypeError: Cannot read property 'manifest' of null
    at lighthouseLib.findByPwaId.then.lighthouse (/Users/jtoledo/GitHub/gulliver/controllers/pwa.js:247:44)
    at process._tickCallback (internal/process/next_tick.js:103:7)
  status: 404,
  response: 'Cannot read property \'manifest\' of null' }

**Comment by juliantoledo** [comment]
I created a branch to keep working on this:
https://github.com/GoogleChrome/gulliver/tree/encoded-start-url
